apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: oh3ieq1kq-nodejs 
  janus-idp.io/tekton: oh3ieq1kq-nodejs
  backstage.io/kubernetes-id: oh3ieq1kq-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: oh3ieq1kq-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml