apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: oh3ieq1kq-nodejs
  janus-idp.io/tekton: oh3ieq1kq-nodejs
  backstage.io/kubernetes-id: oh3ieq1kq-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: oh3ieq1kq-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
